site_name: BinksPals documentation

theme:
  name : material
  language : en
  favicon : images/favicon.ico
  icon:
    logo : material/earth

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true   
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
    - mkdocs-video

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
